#!/bin/sh

# Source function library.
. /etc/init.d/functions

EXEC_PATH="/usr/bin"
SYSREPOPLUGIND_EXEC="sysrepo-plugind"
SERVER_OPTS=" -d -v2"

init_sysrepo() {
    export NP2_MODULE_DIR="/usr/share/yang/modules/netopeer2"
    export LN2_MODULE_DIR="/usr/share/yang/modules/libnetconf2"
    export NP2_MODULE_PERMS="600"
    export NP2_MODULE_OWNER="root"
    export NP2_MODULE_GROUP="root"
    if [ -x /usr/bin/sysrepoctl ]; then
        sh /usr/share/netopeer2/scripts/setup.sh
        sh /etc/sysrepo-tsn/install-tsn-yang.sh
    fi
    if [ -x /usr/bin/sysrepocfg ]; then
        sh /usr/share/netopeer2/scripts/merge_hostkey.sh
        sh /usr/share/netopeer2/scripts/merge_config.sh
    fi
    touch /etc/sysrepo/init
}

case "$1" in
    start)
        test -r /etc/sysrepo/init || init_sysrepo

        echo -n "Starting sysrepo-plugind: "
        start-stop-daemon --start --background --exec $EXEC_PATH/$SYSREPOPLUGIND_EXEC -- $SERVER_OPTS
        RETVAL=$?
        if [ $RETVAL -eq 0 ] ; then
            echo "OK"
        else
            echo "FAIL"
            exit 1
        fi
        ;;
    stop)
        echo -n "Stopping sysrepo-plugind: "
        start-stop-daemon --stop --exec $EXEC_PATH/$SYSREPOPLUGIND_EXEC
        RETVAL=$?
        if [ $RETVAL -eq 0 ] ; then
            echo "OK"
        else
            echo "FAIL"
            exit 1
        fi
        ;;
    status)
        status $SYSREPOPLUGIND_EXEC
        exit $?
        ;;
    restart)
        $0 stop && sleep 1 && $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac

exit 0

