#!/bin/sh

. /etc/init.d/functions

EXEC_PATH="/usr/bin"
SYSREPOTSN_EXEC="sysrepo-tsn"
SERVER_OPTS=" -d"

case "$1" in
    start)
		echo -n "Starting sysrepo-tsn: "
        start-stop-daemon --start --background --exec $EXEC_PATH/$SYSREPOTSN_EXEC -- $SERVER_OPTS
        RETVAL=$?
        if [ $RETVAL -eq 0 ] ; then
            echo "OK"
        else
            echo "FAIL"
            exit 1
        fi
        ;;
    stop)
		echo -n "Stopping sysrepo-tsn: "
        start-stop-daemon --stop --pidfile /var/run/sysrepo-tsn.pid
        RETVAL=$?
        if [ $RETVAL -eq 0 ] ; then
            echo "OK"
        else
            echo "FAIL"
            exit 1
        fi
        ;;
    status)
        status $SYSREPOTSN_EXEC
        exit $?
        ;;
    restart)
        $0 stop && sleep 1 && $0 start
        ;;
   *)
       echo "Usage: $0 {start|stop|status|restart}"
       exit 1
       ;;
esac

exit 0

