# uboot env
# layerscape uboot
UBOOT_BAREMETAL_DEFCONFIG_ls1043ardb ?= "ls1043ardb_bm_defconfig"
UBOOT_BAREMETAL_DEFCONFIG_ls1046ardb ?= "ls1046ardb_bm_defconfig"
UBOOT_BAREMETAL_DEFCONFIG_ls1028ardb ?= "ls1028ardb_bm_defconfig"
UBOOT_BAREMETAL_DEFCONFIG_lx2160ardb ?= "lx2160ardb_bm_defconfig"
UBOOT_BAREMETAL_DEFCONFIG_lx2160ardb-rev2 ?= "lx2160ardb_bm_defconfig"
UBOOT_BAREMETAL_DEFCONFIG_ls1021aiot ?= "ls1021aiot_bm_defconfig"

# imx uboot
UBOOT_BAREMETAL_DEFCONFIG_mx8mp ?= "imx8mp_evk_bm_defconfig"
UBOOT_BAREMETAL_DEFCONFIG_mx8mm ?= "imx8mm_evk_bm_defconfig"