# ============================================================================
# sysrepo-plugins-list.conf
#
# Purpose:
#   This configuration file defines the list of sysrepo plugins that should be
#   loaded by the sysrepo-plugin-daemon at startup.
#
# Usage:
#   - Each non-comment line must contain the filename of a plugin shared
#     library (typically ending in .so).
#   - Plugins are searched in a staging directory(/lib/sysrepo-plugind/staging)
#     and then copied to the standard sysrepo daemon plugins directories
#     (/lib/sysrepo-plugind/plugins/),
#   - Lines starting with '#'are treated as comments and the referenced
#     plugins will NOT be loaded.
#
# Example:
#     lldp-plugin.so      # enabled
#     #ptp-plugin.so      # disabled
# ============================================================================

lldp-plugin.so
ptp-plugin.so
#genavb_gptp-plugin.so
tsn-plugin.so
