#!/bin/sh

# Source function library.
. /etc/init.d/functions

EXEC_PATH="/usr/sbin"
SERVER_EXEC="netopeer2-server"
SERVER_OPTS=" -v 1"


case "$1" in
    start)
        /etc/init.d/sysrepo start
        start-stop-daemon --start --exec $EXEC_PATH/$SERVER_EXEC -- $SERVER_OPTS
        ;;
    stop)
        start-stop-daemon --stop --quiet --exec $EXEC_PATH/$SERVER_EXEC
        ;;
    status)
        status $SERVER_EXEC
        ;;
    reload)
        echo "not supported"
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1;;
esac


exit 0
