#!/bin/bash

set -eu -o pipefail

shopt -s failglob

local_path=$(dirname $0)

echo 830 > /proc/sys/net/ipv4/ip_unprivileged_port_start

if [ -f "/etc/Netopeer2/init.stamp" ]; then
	exit 0
fi

echo "configure sysrepo and netopeer2 ..."

cd /etc/Netopeer2/scripts
./libyang-model-install.sh >/dev/null 2>&1
./keystored-model-install.sh >/dev/null 2>&1
./netopeer2-keystored.sh >/dev/null 2>&1
./server-model-install.sh >/dev/null 2>&1

cd /etc/sysrepo-tsn/scripts
./model-install.sh >/dev/null 2>&1

touch "/etc/Netopeer2/init.stamp"
echo "configure sysrepo and netopeer2 OK"

cd /home/root/
