# Copyright 2024 NXP


SRC_LA9310_HOST_URI = "git://github.com/nxp-qoriq/la93xx_host_sw;protocol=https;nobranch=1;name=host_repo"
SRC_LA9310_FRTOS_URI = "git://github.com/nxp-qoriq/la93xx_freertos;protocol=https;nobranch=1;name=freertos_repo"
SRC_LA9310_FW_URI = " git://github.com/nxp-qoriq/la93xx_firmware;protocol=https;nobranch=1;name=firmware_repo"


SRCREV_host_repo = "449727953ffde7a530998cda9d4e73d57f425e70"
SRCREV_freertos_repo = "94e4eea076e6d9796ccd15e3fcb91fbd2976da63"
SRCREV_firmware_repo = "c298c417f689f0f6709a94d1c75156b1ed2934f5"
